INSERT INTO cellars (id, name, created_at, updated_at)
VALUES (1, "BODEGA SUR",NOW(), NOW())
,      (2, "BODEGA NORTE",NOW(), NOW())
,      (3, "BODEGA OESTE",NOW(), NOW())
,      (4, "BODEGA ESTE",NOW(), NOW());	

INSERT INTO items (id, name, description, created_at, updated_at)
VALUES (1, "AUDIFONOS", "50W", NOW(), NOW())
,      (2, "MONITOR", "22", NOW(), NOW())
,      (3, "TECLADO", "",NOW(), NOW())
,      (4, "MOUSE", "opt", NOW(), NOW())
,      (5, "CARGADOR", "portatil", NOW(), NOW())
,      (6, "DISCO DURO", "", NOW(), NOW())
,      (7, "MEMORIA RAM", "", NOW(), NOW())
,      (8, "PROCESADOR", "", NOW(), NOW())
,      (9, "DISCO DURO", "", NOW(), NOW())
,      (10, "DISCO ESTADO SOLIDO", "", NOW(), NOW());	

INSERT INTO inventories (item_id, cellar_id, quantity, created_at, updated_at)
VALUES (1, 1, 5, NOW(), NOW())
,      (2, 2, 10, NOW(), NOW())
,      (3,3, 25, NOW(), NOW())
,      (4,4, 100, NOW(), NOW())
,      (5,1, 62, NOW(), NOW())
,      (6,2, 22, NOW(), NOW())
,      (7,3, 0, NOW(), NOW())
,      (8,4, 1, NOW(), NOW())
,      (9,1, 12, NOW(), NOW())
,      (10,2, 45, NOW(), NOW())
,      (1,2, 2, NOW(), NOW())
,      (2,1, 4, NOW(), NOW())
,      (3,4, 45, NOW(), NOW())
,      (4,3, 158, NOW(), NOW())
,      (4,1, 13, NOW(), NOW())
,      (4,2, 15, NOW(), NOW())
,      (2,3, 63, NOW(), NOW())
,      (2,4, 85, NOW(), NOW());